#!/bin/sh
set -eu

CONF=/usr/local/etc/dockerbox/dockerbox.conf
INTERFACES=/etc/network/interfaces
IFACE=${DOCKERBOX_IFACE:-enp0s2}
DOCKER_SERVICE=/etc/systemd/system/docker.service.d/override.conf

die() { echo "dockerbox-write-address: $*" >&2; exit 1; }

valid_ip() {
	_o=$IFS; IFS=.; set -- $1; IFS=$_o
	[ $# -eq 4 ] || return 1
	for _octet do
		case $_octet in
		''|*[!0-9]*) return 1 ;;
		esac
		[ "$_octet" -le 255 ] || return 1
	done
}

[ -r "$CONF" ] || die "$CONF not readable"
. "$CONF"

: "${dockerbox_ip:?dockerbox_ip not set in $CONF}"
: "${nat_mask:?nat_mask not set in $CONF}"
: "${nat_ip:?nat_ip not set in $CONF}"

valid_ip "$dockerbox_ip" || die "bad dockerbox_ip: $dockerbox_ip"
valid_ip "$nat_ip"       || die "bad nat_ip: $nat_ip"

case $nat_mask in
''|*[!0-9]*) die "bad nat_mask: $nat_mask" ;;
esac
[ "$nat_mask" -le 32 ] || die "bad nat_mask: $nat_mask"

tmp=$(mktemp "$INTERFACES.XXXXXX")
trap 'rm -f "$tmp"' EXIT

cat > "$tmp" <<EOF
# Generated by dockerbox-write-address. Edits will be overwritten;
# change /usr/local/etc/dockerbox/dockerbox.conf on the host instead.
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet static
    address $dockerbox_ip/$nat_mask
    gateway $nat_ip
EOF

chmod 644 "$tmp"
cmp -s "$tmp" "$INTERFACES" || mv "$tmp" "$INTERFACES"

cat > "$tmp" <<EOF
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://$dockerbox_ip:2375
EOF

chmod 644 "$tmp"
cmp -s "$tmp" "$DOCKER_SERVICE" || mv "$tmp" "$DOCKER_SERVICE"
